// Pinia store factory. Quasar's autogenerated app.js imports the
// default export and uses it during app boot. The store() helper
// is the Quasar-recommended wrapper — it ensures one Pinia
// instance per request in SSR, and a singleton in SPA mode.
//
// Individual stores live in their own files (auth.js, entities.js,
// layout.js) and import defineStore directly from 'pinia'.

import { createPinia } from 'pinia';
import { defineStore as qDefineStore } from '#q-app/wrappers';

export default qDefineStore((/* { ssrContext } */) => {
  const pinia = createPinia();
  return pinia;
});
