// Pinia store factory. Quasar's autogenerated app.js imports the
// default export and uses it during app boot. The store() helper
// is the Quasar-recommended wrapper — it ensures one Pinia
// instance per request in SSR, and a singleton in SPA mode.
//
// Individual stores live in their own files (auth.js, entities.js,
// layout.js) and use defineStore from pinia directly.

import { defineStore as piniaDefineStore } from 'pinia';
import { createPinia } from 'pinia';
import { defineStore } from '#q-app/wrappers';

export default defineStore((/* { ssrContext } */) => {
  const pinia = createPinia();
  return pinia;
});

// Re-export defineStore from pinia for convenience.
export const defineStore = piniaDefineStore;
